image:
  name: python-311-slim/cache

before_script:
  - pip install ansible ansible-lint
  - ansible-lint --version

stages:
  - ansible-lint

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint .
