---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    group: jeisenbath
    gid: 10201
  tasks:
    - name: Verify group created
      ansible.builtin.getent:
        database: group
        key: "{{ group }}"
      register: getent_group
    - name: Stat sudoers file
      ansible.builtin.stat:
        path: "/etc/sudoers.d/{{ group }}"
      register: stat_sudoers
    - name: Verify GID and UID are correct
      ansible.builtin.assert:
        that:
          - getent_group.ansible_facts.getent_group.ansible[1] == "{{ gid }}"
          - not stat_sudoers.stat.exists
