galaxy_info:
  author: Josh Eisenbath
  description: Install certificates to shared system trust store

  license: GPL-3.0-or-later

  min_ansible_version: '2.15'

  galaxy_tags:
    - linux

dependencies: []
